### ISSUE TITLE
Tutorial Content is not align correctly. [bug]

### ISSUE THREAD

**Issue by betterfuture009** [stackbuilders/react-native-spotlight-tour#87] opened 2023-03-06 14:04 UTC
Hello,

I am using this component to implement product guide. It's working as well at first time.
But sometimes content is not align correct on iPhone 12, 13 devices.

It's working as well at iPhone X devices.

https://user-images.githubusercontent.com/36209712/223131360-a243833e-5241-400d-8769-0f7e18616f0f.MP4

This is my code.

const profileSteps = [
  {
    alignTo: Align.SCREEN,
    position: Position.BOTTOM,
    before() {
      return new Promise(resolve => {
        scrollViewRef.scrollTo({y: 0, animated: true});
        resolve();
      });
    },
    render: ({ next }) => (
      <GuideCard 
        description={i18n.t("guides.profile.title")}
        onNext={next}
      />
    )
  },
  {
    alignTo: Align.SCREEN,
    position: Position.TOP,
    before() {
      return new Promise(resolve => {
        scrollViewRef.scrollToEnd({animated: true});
        resolve();
      });
    },
    render: ({ previous, stop }) => (
      <GuideCard 
        description={i18n.t("guides.profile.delete_account")}
        onPrev={previous}
        onStop={() => {
          stop();
          Storage.PROFILE_TUTORIAL.set('true');
        }}
      />
    )
  },
];

**Comment by JoseLion** [comment] 2023-04-24 21:38
Thanks for the report. I remember to have seen this on a previous version right after the animation flow refactor. This was caused by a race condition between the animation flow and a `useEffect(..)` in charge of positioning the tooltip. However, this was corrected with the animation flow refactor. So just in case, can you share with us the following details?
- React Native version
- React version
- React Native Spotlight Tour version
- React Native SVG version

Thanks in advance!

**Comment by JoseLion** [comment] 2023-05-17 21:46
I was able to reproduce it with version **v2.1.0**. We'll be addressing this issue next. Thanks for the report 🙂

**Comment by mjgalawork** [comment] 2023-06-20 08:27
Hi, is there news on this? We see the same problem in our app.

**Comment by JoseLion** [comment] 2023-06-29 23:15
We're currently working on a robust and reliable solution to this issue. It's taking some time for us to piece it together with the current implementation, but we're making good progress 🙂

I'll update this issue as soon as we have any more news.

**Comment by bryanansong** [comment] 2023-09-11 22:22
Hello, are there any updates on how to fix this issue? Thanks

**Comment by JoseLion** [comment] 2023-09-18 21:02
This issue is resolved by #108. However, it comes with some breaking changes on the tooltip configuration props, as we're now deferring that to [Floating UI](https://floating-ui.com/). We'll be releasing the new version this week. Thank you all for the patience and support 🙂

**Comment by JoseLion** [comment] 2023-09-29 19:55
This has been fixed and available since [v3.0.0](https://github.com/stackbuilders/react-native-spotlight-tour/releases/tag/v3.0.0) release.

**Closed by JoseLion** 2023-09-29 19:55 UTC
Labels: bug, help wanted
