### ISSUE TITLE
Documentation url broken

### ISSUE THREAD

**Issue by MoreSaltMoreLemon** [stackbuilders/react-native-spotlight-tour#129] opened 2023-10-09 19:34 UTC
The API Documentation mentioned in the README at [API Reference](https://github.com/stackbuilders/react-native-spotlight-tour#api-reference) refers to a url: https://stackbuilders.github.io/react-native-spotlight-tour/docs/build which does not exist.

![image](https://github.com/stackbuilders/react-native-spotlight-tour/assets/43081278/875157e9-6cb3-4fb8-b639-f52491b3e3b5)

No build/ directory exists within docs/

![image](https://github.com/stackbuilders/react-native-spotlight-tour/assets/43081278/3ca36579-5d4f-46a3-ad50-0860cd366138)

**Comment by beKoool** [comment] 2023-10-10 23:20
Hey, can you assign me?

**Comment by JoseLion** [comment] 2023-10-11 03:04
@MoreSaltMoreLemon, thanks for the report! We don't keep track of the built API Reference docs on Git because it's subject to frequent changes. Instead, we build the docs on the `pages.yml` workflow, which is immediately published to GitHub Pages.

The problem is that we moved the project to a mono-repo structure, and now everything related to the library is in the `package/` folder. However, I forgot to change the [output setting](https://github.com/stackbuilders/react-native-spotlight-tour/blob/e64b9e94716bdab9304519ca76a1dc77d65a31ee/package/typedoc.json#L13) in the `package/typedoc.json` file. So now the API Reference is on this link instead: https://stackbuilders.github.io/react-native-spotlight-tour/package/docs/build/

This should be as simple as changing the `"out": "./docs/build"` property to `"out": "../docs/build"`. @beKoool, feel free to open a PR with this change. All contributions are welcome 🙂

**Comment by beKoool** [comment] 2023-10-12 10:04
Hey @JoseLion, I have fixed the issue in my PR #130 . 

Thank you!

**Comment by JoseLion** [comment] 2023-10-17 14:39
Closed by #130

**Closed by JoseLion** 2023-10-17 14:39 UTC
Labels: bug, documentation, good first issue
