### ISSUE TITLE
Can't use in javaScript  Project

### ISSUE THREAD

**Issue by mmestiyak** [stackbuilders/react-native-spotlight-tour#46] opened 2021-11-25 04:04 UTC
I Wrote my project in javaScript not in typescript, it's not working.
showing the error Element type is invalid: expected a string

**Comment by JoseLion** [comment] 2021-12-28 17:13
@mmestiyak thanks for the report, I'll be looking into it in the next few days 🙂

**Comment by JoseLion** [comment] 2022-01-10 19:30
@mmestiyak I tried to reproduce in a 100% vanilla JavaScript project, and all was working fine. However, during this test, I found an issue on the `AttachStep` component that could be causing the error you mentioned. I pushed a fix for that, so can you please give it another try with version `v1.0.2` 🙂 

If this new version does not solve your issue, can you share the complete logs of the error you're getting and, if possible, some code to reproduce the problem?

Thanks!

**Comment by mmestiyak** [comment] 2022-01-11 05:40
@JoseLion  Thank you so much, i'll test it out and let you know but sorry maybe not immediately i can test and let you know

**Comment by Bimbimz** [comment] 2022-11-19 22:49
do you have the sample code?
because of the following line error:
const tourSteps: TourStep[] =

**Comment by Bimbimz** [comment] 2022-11-19 22:49
> @mmestiyak I tried to reproduce in a 100% vanilla JavaScript project, and all was working fine. However, during this test, I found an issue on the `AttachStep` component that could be causing the error you mentioned. I pushed a fix for that, so can you please give it another try with version `v1.0.2` 🙂
> 
> If this new version does not solve your issue, can you share the complete logs of the error you're getting and, if possible, some code to reproduce the problem?
> 
> Thanks!

do you have the sample code?
because of the following line error:
const tourSteps: TourStep[] =

**Comment by JoseLion** [comment] 2023-10-02 20:44
Here's a sample Expo Snack with vanilla JS and `v3`. If anyone still has similar issues, please update to the latest version and open a separate ticket if the problem persists. Thank you all for the support! 🙂 

https://snack.expo.dev/@jleonstackbuilders/react-native-spotlight-tour-with-vanilla-js

**Closed by JoseLion** 2023-10-02 20:44 UTC
Labels: waiting-for-triage
